# Generated by Django 5.2.4 on 2026-03-26 13:42

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('leave_type', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('sick', 'Sick'), ('vacation', 'Vacation'), ('other', 'Other')], default='paid', help_text='Leave Type', max_length=20)),
                ('leave_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Leave Status', max_length=20)),
                ('start_date', models.DateField(help_text='Start Date')),
                ('end_date', models.DateField(help_text='End Date')),
                ('reason', models.TextField(blank=True, help_text='Reason')),
                ('organization', models.ForeignKey(help_text='Organization', on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='organization.organization')),
                ('user', models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave',
                'verbose_name_plural': 'Leaves',
                'indexes': [models.Index(fields=['user'], name='leave_leave_user_id_fd951a_idx'), models.Index(fields=['organization'], name='leave_leave_organiz_ba74dd_idx')],
            },
        ),
    ]
