# Generated by Django 5.2.4 on 2026-03-26 13:42

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('name', models.CharField(help_text='Organization Name', max_length=255, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Organization Slug', max_length=255, populate_from='name', unique=True)),
                ('description', models.TextField(blank=True, help_text='Organization Description')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'indexes': [models.Index(fields=['name'], name='organizatio_name_2d216c_idx'), models.Index(fields=['slug'], name='organizatio_slug_0d3b5f_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('project_manager', 'Project Manager'), ('team_lead', 'Team Lead'), ('hr_executive', 'HR Executive'), ('employee', 'Employee'), ('member', 'Member'), ('guest', 'Guest')], default='member', help_text='Role', max_length=20)),
                ('organization', models.ForeignKey(help_text='Organization', on_delete=django.db.models.deletion.CASCADE, related_name='organization_users', to='organization.organization')),
                ('user', models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='organization_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization User',
                'verbose_name_plural': 'Organization Users',
                'indexes': [models.Index(fields=['organization'], name='organizatio_organiz_dc4d7f_idx'), models.Index(fields=['user'], name='organizatio_user_id_5d079d_idx')],
                'unique_together': {('organization', 'user')},
            },
        ),
    ]
