# Generated by Django 5.2.4 on 2026-03-27 08:49

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='image',
            field=models.ImageField(blank=True, help_text='Organization Image', null=True, upload_to='organization/images/'),
        ),
        migrations.CreateModel(
            name='OrganizationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('address', models.CharField(blank=True, help_text='Organization Address', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, help_text='Organization Phone', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Organization Email', max_length=254, null=True)),
                ('website', models.URLField(blank=True, help_text='Organization Website', null=True)),
                ('organization', models.OneToOneField(help_text='Organization', on_delete=django.db.models.deletion.CASCADE, related_name='organization_details', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Organization Detail',
                'verbose_name_plural': 'Organization Details',
                'indexes': [models.Index(fields=['organization'], name='organizatio_organiz_cdb73b_idx')],
            },
        ),
    ]
