# Generated by Django 5.2.4 on 2026-03-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_image_organizationdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email_domain',
            field=models.CharField(blank=True, help_text='Email domain of the organization (e.g. company.com)', max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['email_domain'], name='organizatio_email_d_dd0c44_idx'),
        ),
    ]
