# Generated by Django 5.2.4 on 2026-03-26 13:42

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('is_html', models.BooleanField(default=False)),
                ('email_type', models.CharField(choices=[('welcome', 'Welcome'), ('email_otp_verify', 'Email OTP Verify'), ('email_verified', 'Email Verified'), ('password_reset', 'Password Reset'), ('password_change', 'Password Change'), ('password_reset_link', 'Password Reset Link'), ('password_reset_success', 'Password Reset Success'), ('invite_user', 'Invite User')], help_text='Email Type', max_length=255)),
                ('subject', models.CharField(help_text='Subject', max_length=255)),
                ('body', models.TextField(help_text='Body', verbose_name='Body')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Email successfully verified or password updated after invite.'),
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_otp', models.CharField(db_column='otp', editable=False, help_text='The Protected OTP instance.', max_length=255, verbose_name='OTP')),
                ('key', models.CharField(help_text='The OTP key used for authentication.', max_length=255, verbose_name='Key')),
                ('otp_type', models.CharField(choices=[('signup', 'Signup OTP'), ('forgot-password', 'Forgot Password OTP'), ('reset-password', 'Reset Password OTP')], help_text='The type of OTP key. This can be Email, SMS, Registration, or Login.', max_length=50, verbose_name='OTP Type')),
                ('expired_at', models.DateTimeField(blank=True, help_text='The date and time when the OTP key expires.(in seconds)', null=True, verbose_name='Expired At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], default='pending', help_text='The status of the OTP key, e.g., Pending & Verified.', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the OTP key was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the OTP key was last updated.', verbose_name='Updated At')),
                ('user', models.ForeignKey(help_text='The user associated with this OTP key.', on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'OTP Key',
                'verbose_name_plural': 'OTP Keys',
                'abstract': False,
                'unique_together': {('user', 'otp_type', 'key')},
            },
        ),
    ]
